#!/bin/bash
#SBATCH -N 1        # request 1 nodes
#SBATCH -p fat      # request partition 'fat', 
#SBATCH -n 1 -c 4   # request 4 cores on 1 node
#SBATCH -t 10:20:30 # 10 hours plus 20 minutes plus 30 seconds
source ~/env/paths
python3 ipengine_chief -t SLURM -a 10.0.200.14 -p 30016

